## Get to know the data

In [1]:
#import the data shit
from IPython.display import display as d
from pandas.io.formats.info import DataFrameInfoPrinter
import os
import pandas as pd
import numpy as np
import pandas as pd
#import the decision tree shit
#getting to the data directory
data_dir = 'devided_dataset_v2'
categories = ['CDs_and_Vinyl', 'Grocery_and_Gourmet_Food', 'Toys_and_Games']

In [2]:
#getting the products and the reviews for the shit
resultpath = os.path.join(data_dir, categories[0], 'train', 'product_training.json')
trainingpath = os.path.join(data_dir, categories[0], 'train', 'review_training.json')
#reading the file with json
reviewdata = pd.read_json(trainingpath)
resultpath = pd.read_json(resultpath)

In [3]:
#combine the 2 shits together
fulldata = resultpath.merge(reviewdata, how='outer', on='asin')

In [4]:
#run this once and dont touch
fulldata.drop('style', axis = 1, inplace = True)
fulldata.drop('unixReviewTime', axis = 1, inplace = True)
fulldata.drop('reviewTime', axis = 1, inplace = True)
fulldata.drop('reviewerID', axis = 1, inplace = True)
fulldata.drop('reviewerName', axis = 1, inplace = True)
fulldata = fulldata.replace(True, 1)
fulldata = fulldata.replace(False, 0)
fulldata = fulldata.fillna(0)

In [5]:
column_to_move = fulldata.pop("awesomeness")
# insert column with insert(location, column_name, column_value)
fulldata.insert(6, "awesomeness", column_to_move)

In [6]:
fulldata

,asin,vote,verified,reviewText,summary,image,awesomeness
0,0000B049F5B33CD310EB1AB236E20191,0,1,"Even tho I love this album, I am having proble...",I LOVE NANCY,0,1
1,0000B049F5B33CD310EB1AB236E20191,0,0,I LOVE IT!!!,Five Stars,0,1
2,0000B049F5B33CD310EB1AB236E20191,0,1,Nancy Wilson is still one of the most distinct...,"THE BEAUTIFUL LEGEND, NANCY WILSON, HER EXCELL...",0,1
3,0000B049F5B33CD310EB1AB236E20191,6,0,Having been a Nancy Wilson fan for over twenty...,The Ultimate Song Stylist Scores Again,0,1
4,00018184A9EC4D270219A296B2580303,22,0,"The musical genre of dance/electronica is, at ...",Struggle for Pleasure,0,0
...,...,...,...,...,...,...,...
770781,FFFF5A3D9CB0B40FF0FE6B95F05D26FE,5,0,a come back from the very suscessful last albu...,"better instrumentation, but worse melodies.",0,1
770782,FFFF5A3D9CB0B40FF0FE6B95F05D26FE,3,0,"Welll first thier young and hopeless, and suck...",Still horrible.,0,1
770783,FFFF5A3D9CB0B40FF0FE6B95F05D26FE,0,0,So I'm riding to work with this dude. Nice br...,Good Charoleete Good Day,0,1
770784,FFFF5A3D9CB0B40FF0FE6B95F05D26FE,3,0,"Oh s**t, first they TRIED to be punk and now t...",Worse than their first two,0,1
770785,FFFF5A3D9CB0B40FF0FE6B95F05D26FE,0,0,"YEAH, these guys now how to PUNK or F*** YOUR ...",BEST PUNK ROCK/ROCK CD EVUH!!!!,0,1

In [7]:
fulldata.describe()

            verified    awesomeness
count  770786.000000  770786.000000
mean        0.520776       0.542694
std         0.499568       0.498174
min         0.000000       0.000000
25%         0.000000       0.000000
50%         1.000000       1.000000
75%         1.000000       1.000000
max         1.000000       1.000000

In [18]:
# ## import models
# from sklearn.linear_model import LinearRegression
# from sklearn.naive_bayes import GaussianNB
# from sklearn import tree
# from sklearn.feature_extraction.text import HashingVectorizer

# #import training and testing 
# from sklearn.model_selection import train_test_split

In [16]:
# #fire it up
# LinReg = LinearRegression()
# NivBay = GaussianNB()
# DTree = tree.DecisionTreeClassifier()
# #split input and output
# X = fulldata.iloc[:,0:6]
# Y = fulldata.iloc[:,6]
# #SHUFFLE
# Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,Y, test_size = 0.2, random_state = 1)

In [ ]:
#AGGREGATE DATA WORKSPACE